### ISSUE TITLE
Protect `main`  and `dev`

### ISSUE THREAD

**Issue by ArthurWalraven** [AInnervate/TinyNets.jl#12]
We should have at least some basic protection for those branches. I'd suggest
- "Require PR before merging" (both),
- "Require approvals": 1 for `dev` and 3 for `main`, and
- "Do not allow bypassing the above settings" (both).

Only @natema can do this one.

**Comment by natema** [comment]
I've put one approval for main since the typical PR will be from dev, which already undergo a review round.
I also keep the right to bypass. I'm the only one who can and if I want I could equivalently disactivate such setting on the spot. I think it makes sense only after we can have different roles with an organization.

**Comment by natema** [comment]
(@ArthurWalraven I let you close the issue if you agree or tell me otherwise if you had a strong opinion on the OP).

**Comment by natema** [comment]
Closing, since now co-owners can change these settings.
